FROM node:14.15.0
EXPOSE 8000
RUN apt-get update -y
RUN apt-get install chromium -y
RUN npm install --quiet -g gatsby-cli
WORKDIR /app
COPY ./package.json .
RUN npm install
COPY . .
RUN gatsby clean
CMD ["gatsby", "develop", "-H", "0.0.0.0" ]