FROM circleci/node:14.15.0-browsers
EXPOSE 8000
RUN sudo apt-get update -y
RUN sudo apt-get install chromium -y
RUN sudo npm install --quiet -g gatsby-cli
WORKDIR /app
COPY ./package.json .
COPY ./package-lock.json .
RUN npm install
COPY . .
RUN gatsby clean
CMD ["gatsby", "develop", "-H", "0.0.0.0" ]